# Generated by Django 5.2.5 on 2025-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='student_profile/default.jpg', null=True, upload_to='student_profile/avatars'),
        ),
    ]
