# Generated by Django 5.2.7 on 2025-10-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_grades'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course'),
        ),
    ]
