# Generated by Django 5.2.7 on 2025-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_grades_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ['-average_score']},
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late')], default='submitted', max_length=30),
        ),
    ]
